//! OpenAPI document assembly.

use utoipa::openapi::security::{Http, HttpAuthScheme, SecurityScheme};
use utoipa::{Modify, OpenApi};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "AsterYggdrasil API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Self-hosted Minecraft skin site and Yggdrasil authentication server.",
        license(name = "MIT"),
    ),
    modifiers(&SecurityAddon),
    paths(
        crate::api::routes::health::health,
        crate::api::routes::health::ready,

        crate::api::routes::auth::check,
        crate::api::routes::auth::setup,
        crate::api::routes::auth::register,
        crate::api::routes::auth::login,
        crate::api::routes::auth::refresh,
        crate::api::routes::auth::logout,
        crate::api::routes::auth::me,
        crate::api::routes::auth::patch_profile,
        crate::api::routes::auth::upload_avatar,
        crate::api::routes::auth::put_avatar_source,
        crate::api::routes::auth::get_self_avatar,
        crate::api::routes::auth::sessions,
        crate::api::routes::auth::delete_other_sessions,
        crate::api::routes::auth::delete_session,
        crate::api::routes::auth::list_passkeys,
        crate::api::routes::auth::start_passkey_registration,
        crate::api::routes::auth::finish_passkey_registration,
        crate::api::routes::auth::rename_passkey,
        crate::api::routes::auth::delete_passkey,
        crate::api::routes::auth::start_passkey_login,
        crate::api::routes::auth::finish_passkey_login,

        crate::api::routes::auth_external_auth::list_providers,
        crate::api::routes::auth_external_auth::list_providers_by_kind,
        crate::api::routes::auth_external_auth::start_login,
        crate::api::routes::auth_external_auth::finish_login,
        crate::api::routes::auth_external_auth::start_email_verification,
        crate::api::routes::auth_external_auth::confirm_email_verification,
        crate::api::routes::auth_external_auth::link_with_password,
        crate::api::routes::auth_external_auth::list_links,
        crate::api::routes::auth_external_auth::delete_link,

        crate::api::routes::profiles::list_minecraft_profiles,
        crate::api::routes::profiles::create_minecraft_profile,
        crate::api::routes::profiles::rename_minecraft_profile,
        crate::api::routes::profiles::list_minecraft_profile_textures,
        crate::api::routes::profiles::bind_minecraft_profile_texture,
        crate::api::routes::profiles::unbind_minecraft_profile_texture,
        crate::api::routes::profiles::delete_minecraft_profile,
        crate::api::routes::wardrobe::list_wardrobe_textures,
        crate::api::routes::wardrobe::upload_wardrobe_texture,
        crate::api::routes::wardrobe::delete_wardrobe_texture,

        crate::api::routes::public::frontend_config,

        crate::api::routes::yggdrasil::metadata,
        crate::api::routes::yggdrasil::authenticate,
        crate::api::routes::yggdrasil::refresh,
        crate::api::routes::yggdrasil::validate,
        crate::api::routes::yggdrasil::invalidate,
        crate::api::routes::yggdrasil::signout,
        crate::api::routes::yggdrasil::profiles_by_names,
        crate::api::routes::yggdrasil::join,
        crate::api::routes::yggdrasil::has_joined,
        crate::api::routes::yggdrasil::profile_by_uuid,
        crate::api::routes::yggdrasil::texture::upload_texture,
        crate::api::routes::yggdrasil::texture::delete_texture,
        crate::api::routes::yggdrasil::texture::texture_by_hash,

        crate::api::routes::admin::config::list_config,
        crate::api::routes::admin::system_info::get_system_info,
        crate::api::routes::admin::config::config_schema,
        crate::api::routes::admin::config::config_template_variables,
        crate::api::routes::admin::config::get_config,
        crate::api::routes::admin::config::set_config,
        crate::api::routes::admin::config::delete_config,
        crate::api::routes::admin::config::execute_config_action,
        crate::api::routes::admin::audit_logs::list_audit_logs,
        crate::api::routes::admin::tasks::list_tasks,
        crate::api::routes::admin::tasks::retry_task,
        crate::api::routes::admin::tasks::cleanup_tasks,
        crate::api::routes::admin::users::list_users,
        crate::api::routes::admin::users::create_user,
        crate::api::routes::admin::users::get_user,
        crate::api::routes::admin::users::update_user,
        crate::api::routes::admin::users::revoke_user_sessions,
        crate::api::routes::admin::users::get_user_avatar,
        crate::api::routes::admin::profiles::list_minecraft_profiles,
        crate::api::routes::admin::profiles::get_minecraft_profile,
        crate::api::routes::admin::profiles::rename_minecraft_profile,
        crate::api::routes::admin::profiles::delete_minecraft_profile,
        crate::api::routes::admin::profiles::list_minecraft_profile_textures,
        crate::api::routes::admin::profiles::delete_minecraft_profile_texture,
        crate::api::routes::admin::profiles::delete_minecraft_textures_by_hash,
        crate::api::routes::admin::profiles::list_user_minecraft_profiles,
        crate::api::routes::admin::external_auth::list_external_auth_provider_kinds,
        crate::api::routes::admin::external_auth::list_external_auth_providers,
        crate::api::routes::admin::external_auth::create_external_auth_provider,
        crate::api::routes::admin::external_auth::test_external_auth_provider_params,
        crate::api::routes::admin::external_auth::get_external_auth_provider,
        crate::api::routes::admin::external_auth::update_external_auth_provider,
        crate::api::routes::admin::external_auth::delete_external_auth_provider,
        crate::api::routes::admin::external_auth::test_external_auth_provider,

    ),
    components(
        schemas(
            crate::api::error_code::AsterErrorCode,
            crate::api::response::ApiErrorInfo,
            crate::api::response::HealthResponse,
            crate::api::response::SystemInfoResponse,

            crate::api::dto::CheckResp,
            crate::api::dto::SetupReq,
            crate::api::dto::RegisterReq,
            crate::api::dto::LoginReq,
            crate::api::dto::RefreshReq,
            crate::api::dto::LogoutReq,
            crate::api::dto::LogoutResp,
            crate::api::dto::UpdateProfileReq,
            crate::api::dto::UpdateAvatarSourceReq,
            crate::api::dto::PasskeyRegisterStartReq,
            crate::api::dto::PasskeyRegisterFinishReq,
            crate::api::dto::PatchPasskeyReq,
            crate::api::dto::PasskeyLoginStartReq,
            crate::api::dto::PasskeyLoginFinishReq,
            crate::api::dto::StartExternalAuthReq,
            crate::api::dto::ExternalAuthCallbackQuery,
            crate::api::dto::SetConfigReq,
            crate::api::dto::ExecuteConfigActionReq,
            crate::api::dto::ExecuteConfigActionResp,
            crate::api::dto::AdminTaskCleanupReq,
            crate::api::dto::AdminTaskListQuery,
            crate::api::dto::AdminUserListQuery,
            crate::api::dto::CreateAdminUserReq,
            crate::api::dto::UpdateAdminUserReq,
            crate::api::dto::AdminAuditLogSortQuery,
            crate::api::dto::AdminMinecraftProfileListQuery,
            crate::api::dto::RemovedCountResponse,
            crate::api::dto::CreateExternalAuthProviderReq,
            crate::api::dto::UpdateExternalAuthProviderReq,
            crate::api::dto::ExternalAuthProviderTestParamsReq,
            crate::api::dto::BindMinecraftTextureReq,
            crate::api::dto::yggdrasil::CreateMinecraftProfileReq,
            crate::api::dto::yggdrasil::RenameMinecraftProfileReq,
            crate::api::dto::yggdrasil::YggdrasilAgentReq,
            crate::api::dto::yggdrasil::YggdrasilAuthenticateReq,
            crate::api::dto::yggdrasil::YggdrasilAuthenticateResp,
            crate::api::dto::yggdrasil::YggdrasilErrorBody,
            crate::api::dto::yggdrasil::YggdrasilHasJoinedQuery,
            crate::api::dto::yggdrasil::YggdrasilJoinReq,
            crate::api::dto::yggdrasil::YggdrasilMeta,
            crate::api::dto::yggdrasil::YggdrasilMetaResp,
            crate::api::dto::yggdrasil::YggdrasilProfile,
            crate::api::dto::yggdrasil::YggdrasilProfileProperty,
            crate::api::dto::yggdrasil::YggdrasilProfileQuery,
            crate::api::dto::yggdrasil::YggdrasilRefreshReq,
            crate::api::dto::yggdrasil::YggdrasilRefreshResp,
            crate::api::dto::yggdrasil::YggdrasilSignoutReq,
            crate::api::dto::yggdrasil::YggdrasilTokenReq,
            crate::api::dto::yggdrasil::YggdrasilUser,
            crate::services::texture_service::MinecraftTextureMetadata,
            crate::services::texture_service::MinecraftWardrobeTextureMetadata,
            crate::services::yggdrasil_service::MinecraftProfileInfo,

            crate::services::auth_service::AuthUserInfo,
            crate::services::auth_service::AdminUserInfo,
            crate::services::auth_service::AuthSessionInfo,
            crate::services::auth_service::AuthTokenResponse,
            crate::services::auth_service::AccessClaims,
            crate::services::profile_service::AvatarInfo,
            crate::services::profile_service::UserProfileInfo,
            crate::services::passkey_service::PasskeyInfo,
            crate::services::passkey_service::PasskeyRegisterStartResp,
            crate::services::passkey_service::PasskeyLoginStartResp,
            crate::services::external_auth_service::ExternalAuthPublicProvider,
            crate::services::external_auth_service::ExternalAuthProviderKindInfo,
            crate::services::external_auth_service::AdminExternalAuthProviderInfo,
            crate::services::external_auth_service::ExternalAuthProviderTestCheck,
            crate::services::external_auth_service::ExternalAuthProviderTestResult,
            crate::services::external_auth_service::ExternalAuthStartLoginResponse,
            crate::api::routes::auth_external_auth::ExternalAuthFinishLoginResponse,
            crate::services::config_service::ConfigSchemaItem,
            crate::services::config_service::ConfigSchemaOption,
            crate::services::config_service::ConfigActionType,
            crate::services::config_service::PublicBranding,
            crate::services::config_service::PublicFrontendConfig,
            crate::services::config_service::PublicYggdrasilConfig,
            crate::services::config_service::SystemConfig,
            crate::services::config_service::SystemConfigUpdateResult,
            crate::services::config_service::SystemConfigValue,
            crate::services::config_service::SystemConfigWarning,
            crate::services::config_service::TemplateVariableGroup,
            crate::services::config_service::TemplateVariableItem,
            crate::services::audit_service::AuditLogEntry,
            crate::services::audit_service::AuditLogFilterQuery,
            crate::services::audit_service::AuditPresentation,
            crate::services::audit_service::AuditPresentationMessage,
            crate::services::audit_service::AuditUserSummary,
            crate::api::pagination::LimitOffsetQuery,
            crate::api::pagination::SortOrder,
            crate::api::pagination::AdminTaskSortBy,
            crate::api::pagination::AdminUserSortBy,
            crate::api::pagination::AdminAuditLogSortBy,
            crate::api::pagination::OffsetPage<crate::services::config_service::SystemConfig>,
            crate::api::pagination::OffsetPage<crate::services::external_auth_service::AdminExternalAuthProviderInfo>,
            crate::api::pagination::OffsetPage<crate::services::auth_service::AdminUserInfo>,
            crate::api::pagination::OffsetPage<crate::services::task_service::types::TaskInfo>,
            crate::api::pagination::OffsetPage<crate::services::audit_service::AuditLogEntry>,
            crate::api::pagination::OffsetPage<crate::services::yggdrasil_service::MinecraftProfileInfo>,
            crate::services::task_service::types::RuntimeSystemHealthComponent,
            crate::services::task_service::types::RuntimeSystemHealthResult,
            crate::services::task_service::types::RuntimeSystemHealthStatus,
            crate::services::task_service::types::RuntimeTaskPayload,
            crate::services::task_service::types::RuntimeTaskResult,
            crate::services::task_service::types::TaskCreatorSummary,
            crate::services::task_service::types::TaskInfo,
            crate::services::task_service::types::TaskPayload,
            crate::services::task_service::types::TaskPresentation,
            crate::services::task_service::types::TaskPresentationCode,
            crate::services::task_service::types::TaskPresentationMessage,
            crate::services::task_service::types::TaskResult,
            crate::services::task_service::types::TaskStepInfo,
            crate::services::task_service::types::TaskStepStatus,

            crate::entities::audit_log::Model,
            crate::entities::auth_session::Model,
            crate::entities::background_task::Model,
            crate::entities::external_auth_provider::Model,
            crate::entities::mail_outbox::Model,
            crate::entities::minecraft_profile::Model,
            crate::entities::minecraft_profile_texture::Model,
            crate::entities::minecraft_texture::Model,
            crate::entities::system_config::Model,
            crate::entities::user::Model,

            crate::types::UserRole,
            crate::types::UserStatus,
            crate::types::AvatarSource,
            crate::types::ExternalAuthKind,
            crate::types::SystemConfigSource,
            crate::types::SystemConfigValueType,
            crate::types::SystemConfigVisibility,
            crate::types::BackgroundTaskKind,
            crate::types::BackgroundTaskStatus,
            crate::types::MailOutboxStatus,
            crate::types::MailTemplateCode,
            crate::types::AuditAction,
            crate::types::AuditEntityType,
            crate::types::MinecraftTextureModel,
            crate::types::MinecraftTextureType,
        ),
    ),
    tags(
        (name = "auth", description = "Authentication"),
        (name = "external-auth", description = "External authentication"),
        (name = "profiles", description = "Current-user Minecraft profiles"),
        (name = "public", description = "Public frontend bootstrap config"),
        (name = "yggdrasil", description = "Yggdrasil and authlib-injector compatible endpoints"),
        (name = "admin", description = "Administrator operations"),
        (name = "health", description = "Health checks"),
    ),
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "bearer",
            SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
        );
    }
}
