//! OpenAPI document assembly.

use utoipa::openapi::security::{Http, HttpAuthScheme, SecurityScheme};
use utoipa::{Modify, OpenApi};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "AsterYggdrasil API",
        version = env!("ASTER_BUILD_VERSION"),
        description = "Self-hosted Minecraft skin site and Yggdrasil authentication server.",
        license(name = "MIT"),
    ),
    modifiers(&SecurityAddon),
    paths(
        crate::api::routes::health::health,
        crate::api::routes::health::ready,

        crate::api::routes::auth::check,
        crate::api::routes::auth::captcha_policy,
        crate::api::routes::auth::issue_captcha,
        crate::api::routes::auth::setup,
        crate::api::routes::auth::register,
        crate::api::routes::auth::resend_register_activation,
        crate::api::routes::auth::confirm_contact_verification,
        crate::api::routes::auth::request_password_reset,
        crate::api::routes::auth::confirm_password_reset,
        crate::api::routes::auth::change_password,
        crate::api::routes::auth::set_local_password,
        crate::api::routes::auth::verify_user_invitation,
        crate::api::routes::auth::accept_user_invitation,
        crate::api::routes::auth::login,
        crate::api::routes::auth::refresh,
        crate::api::routes::auth::logout,
        crate::api::routes::auth::me,
        crate::api::routes::auth::request_email_change,
        crate::api::routes::auth::resend_email_change,
        crate::api::routes::auth::patch_profile,
        crate::api::routes::auth::upload_avatar,
        crate::api::routes::auth::put_avatar_source,
        crate::api::routes::auth::get_self_avatar,
        crate::api::routes::auth::sessions,
        crate::api::routes::auth::delete_other_sessions,
        crate::api::routes::auth::delete_session,
        crate::api::routes::auth::list_passkeys,
        crate::api::routes::auth::start_passkey_registration,
        crate::api::routes::auth::finish_passkey_registration,
        crate::api::routes::auth::rename_passkey,
        crate::api::routes::auth::delete_passkey,
        crate::api::routes::auth::start_passkey_login,
        crate::api::routes::auth::finish_passkey_login,

        crate::api::routes::account::overview,
        crate::api::routes::account::list_audit_logs,
        crate::api::routes::account::list_user_bans,

        crate::api::routes::auth_external_auth::list_providers,
        crate::api::routes::auth_external_auth::list_providers_by_kind,
        crate::api::routes::auth_external_auth::start_login,
        crate::api::routes::auth_external_auth::finish_login,
        crate::api::routes::auth_external_auth::start_email_verification,
        crate::api::routes::auth_external_auth::confirm_email_verification,
        crate::api::routes::auth_external_auth::link_with_password,
        crate::api::routes::auth_external_auth::list_links,
        crate::api::routes::auth_external_auth::delete_link,

        crate::api::routes::profiles::list_minecraft_profiles,
        crate::api::routes::profiles::create_minecraft_profile,
        crate::api::routes::profiles::rename_minecraft_profile,
        crate::api::routes::profiles::list_minecraft_profile_textures,
        crate::api::routes::profiles::bind_minecraft_profile_texture,
        crate::api::routes::profiles::unbind_minecraft_profile_texture,
        crate::api::routes::profiles::delete_minecraft_profile,
        crate::api::routes::wardrobe::list_wardrobe_textures,
        crate::api::routes::wardrobe::list_texture_library_tags,
        crate::api::routes::wardrobe::update_wardrobe_texture,
        crate::api::routes::wardrobe::replace_wardrobe_texture_tags,
        crate::api::routes::wardrobe::submit_texture_library_review,
        crate::api::routes::wardrobe::withdraw_texture_library_submission,
        crate::api::routes::wardrobe::upload_wardrobe_texture,
        crate::api::routes::wardrobe::delete_wardrobe_texture,
        crate::api::routes::texture_library::list_public_texture_library_tags,
        crate::api::routes::texture_library::list_public_textures,
        crate::api::routes::texture_library::get_public_texture,
        crate::api::routes::texture_library::copy_public_texture,
        crate::api::routes::texture_library::create_texture_report,
        crate::api::routes::texture_preview::texture_preview_by_hash,

        crate::api::routes::public::frontend_config,

        crate::api::routes::yggdrasil::metadata,
        crate::api::routes::yggdrasil::authenticate,
        crate::api::routes::yggdrasil::refresh,
        crate::api::routes::yggdrasil::validate,
        crate::api::routes::yggdrasil::invalidate,
        crate::api::routes::yggdrasil::signout,
        crate::api::routes::yggdrasil::profiles_by_names,
        crate::api::routes::yggdrasil::join,
        crate::api::routes::yggdrasil::has_joined,
        crate::api::routes::yggdrasil::profile_by_uuid,
        crate::api::routes::yggdrasil::minecraft_services::player_certificates,
        crate::api::routes::yggdrasil::minecraft_services::privileges,
        crate::api::routes::yggdrasil::minecraft_services::player_attributes,
        crate::api::routes::yggdrasil::minecraft_services::privacy_blocklist,
        crate::api::routes::yggdrasil::minecraft_services::blocked_servers,
        crate::api::routes::yggdrasil::texture::upload_texture,
        crate::api::routes::yggdrasil::texture::delete_texture,
        crate::api::routes::yggdrasil::texture::texture_by_hash,
        crate::api::routes::yggdrasil::texture::forwarded_texture_by_hash,

        crate::api::routes::admin::config::list_config,
        crate::api::routes::admin::overview::get_overview,
        crate::api::routes::admin::system_info::get_system_info,
        crate::api::routes::admin::config::config_schema,
        crate::api::routes::admin::config::config_template_variables,
        crate::api::routes::admin::config::get_config,
        crate::api::routes::admin::config::set_config,
        crate::api::routes::admin::config::delete_config,
        crate::api::routes::admin::config::execute_config_action,
        crate::api::routes::admin::audit_logs::list_audit_logs,
        crate::api::routes::admin::tasks::list_tasks,
        crate::api::routes::admin::tasks::retry_task,
        crate::api::routes::admin::tasks::cleanup_tasks,
        crate::api::routes::admin::texture_library::list_texture_library_textures,
        crate::api::routes::admin::texture_library::get_texture_library_texture,
        crate::api::routes::admin::texture_library::delete_texture_library_texture,
        crate::api::routes::admin::texture_library::approve_texture_library_texture,
        crate::api::routes::admin::texture_library::reject_texture_library_texture,
        crate::api::routes::admin::texture_library::unpublish_texture_library_texture,
        crate::api::routes::admin::texture_library::list_texture_library_reports,
        crate::api::routes::admin::texture_library::get_texture_library_report,
        crate::api::routes::admin::texture_library::accept_texture_library_report,
        crate::api::routes::admin::texture_library::reject_texture_library_report,
        crate::api::routes::admin::texture_library::list_texture_library_tags,
        crate::api::routes::admin::texture_library::create_texture_library_tag,
        crate::api::routes::admin::texture_library::update_texture_library_tag,
        crate::api::routes::admin::texture_library::delete_texture_library_tag,
        crate::api::routes::admin::users::list_users,
        crate::api::routes::admin::users::create_user,
        crate::api::routes::admin::users::list_user_invitations,
        crate::api::routes::admin::users::create_user_invitation,
        crate::api::routes::admin::users::revoke_user_invitation,
        crate::api::routes::admin::users::get_user,
        crate::api::routes::admin::users::update_user,
        crate::api::routes::admin::users::delete_user,
        crate::api::routes::admin::users::revoke_user_sessions,
        crate::api::routes::admin::user_bans::list_user_bans,
        crate::api::routes::admin::user_bans::get_user_ban,
        crate::api::routes::admin::user_bans::create_user_ban,
        crate::api::routes::admin::user_bans::update_user_ban,
        crate::api::routes::admin::user_bans::revoke_user_ban,
        crate::api::routes::admin::user_bans::list_user_ban_events,
        crate::api::routes::admin::avatars::get_user_avatar,
        crate::api::routes::admin::profiles::list_minecraft_profiles,
        crate::api::routes::admin::profiles::get_minecraft_profile,
        crate::api::routes::admin::profiles::rename_minecraft_profile,
        crate::api::routes::admin::profiles::delete_minecraft_profile,
        crate::api::routes::admin::profiles::list_minecraft_profile_textures,
        crate::api::routes::admin::profiles::delete_minecraft_profile_texture,
        crate::api::routes::admin::profiles::delete_minecraft_textures_by_hash,
        crate::api::routes::admin::profiles::list_user_minecraft_profiles,
        crate::api::routes::admin::external_auth::list_external_auth_provider_kinds,
        crate::api::routes::admin::external_auth::list_external_auth_providers,
        crate::api::routes::admin::external_auth::create_external_auth_provider,
        crate::api::routes::admin::external_auth::test_external_auth_provider_params,
        crate::api::routes::admin::external_auth::get_external_auth_provider,
        crate::api::routes::admin::external_auth::update_external_auth_provider,
        crate::api::routes::admin::external_auth::delete_external_auth_provider,
        crate::api::routes::admin::external_auth::test_external_auth_provider,
        crate::api::routes::admin::yggdrasil::list_session_forward_servers,
        crate::api::routes::admin::yggdrasil::get_session_forward_server,
        crate::api::routes::admin::yggdrasil::create_session_forward_server,
        crate::api::routes::admin::yggdrasil::update_session_forward_server,
        crate::api::routes::admin::yggdrasil::delete_session_forward_server,

    ),
    components(
        schemas(
            crate::api::error_code::AsterErrorCode,
            crate::api::response::ApiErrorInfo,
            crate::api::response::HealthResponse,
            crate::api::response::SystemInfoResponse,

            crate::api::dto::CheckResp,
            crate::api::dto::PublicCaptchaPolicyResp,
            crate::api::dto::SetupReq,
            crate::api::dto::RegisterReq,
            crate::api::dto::ResendRegisterActivationReq,
            crate::api::dto::AcceptUserInvitationReq,
            crate::api::dto::SetLocalPasswordReq,
            crate::api::dto::ActionMessageResp,
            crate::api::dto::LoginReq,
            crate::api::dto::RefreshReq,
            crate::api::dto::LogoutReq,
            crate::api::dto::LogoutResp,
            crate::api::dto::UpdateProfileReq,
            crate::api::dto::UpdateAvatarSourceReq,
            crate::api::dto::PasskeyRegisterStartReq,
            crate::api::dto::PasskeyRegisterFinishReq,
            crate::api::dto::PatchPasskeyReq,
            crate::api::dto::PasskeyLoginStartReq,
            crate::api::dto::PasskeyLoginFinishReq,
            crate::api::dto::AccountOverviewResp,
            crate::api::dto::AccountAuditLogFilterQuery,
            crate::api::dto::AccountUserBanInfo,
            crate::api::dto::AccountUserBanListQuery,
            crate::api::dto::StartExternalAuthReq,
            crate::api::dto::ExternalAuthCallbackQuery,
            crate::api::dto::SetConfigReq,
            crate::api::dto::ExecuteConfigActionReq,
            crate::api::dto::ExecuteConfigActionResp,
            crate::api::dto::AdminTaskCleanupReq,
            crate::api::dto::AdminTaskListQuery,
            crate::api::dto::AdminUserListQuery,
            crate::api::dto::AdminUserBanListQuery,
            crate::api::dto::CreateAdminUserReq,
            crate::api::dto::CreateUserBanReq,
            crate::api::dto::CreateUserInvitationReq,
            crate::api::dto::UpdateUserBanReq,
            crate::api::dto::RevokeUserBanReq,
            crate::api::dto::UpdateAdminUserReq,
            crate::api::dto::AdminMinecraftProfileListQuery,
            crate::api::dto::RemovedCountResponse,
            crate::api::dto::CreateExternalAuthProviderReq,
            crate::api::dto::UpdateExternalAuthProviderReq,
            crate::api::dto::ExternalAuthProviderTestParamsReq,
            crate::api::dto::BindMinecraftTextureReq,
            crate::api::dto::UpdateWardrobeTextureReq,
            crate::api::dto::CopyPublicTextureReq,
            crate::api::dto::ReplaceWardrobeTextureTagsReq,
            crate::api::dto::ReviewTextureLibraryTextureReq,
            crate::api::dto::CreateTextureReportReq,
            crate::api::dto::HandleTextureReportReq,
            crate::api::dto::CreateMinecraftTextureTagReq,
            crate::api::dto::UpdateMinecraftTextureTagReq,
            crate::api::routes::texture_library::PublicTextureLibraryQuery,
            crate::api::routes::admin::texture_library::AdminTextureLibraryTextureQuery,
            crate::api::routes::admin::texture_library::AdminTextureReportQuery,
            crate::api::dto::CreateMinecraftProfileReq,
            crate::api::dto::CurrentMinecraftProfileListQuery,
            crate::api::dto::RenameMinecraftProfileReq,
            crate::api::dto::yggdrasil::YggdrasilAgentReq,
            crate::api::dto::yggdrasil::YggdrasilAuthenticateReq,
            crate::api::dto::yggdrasil::YggdrasilAuthenticateResp,
            crate::api::dto::yggdrasil::YggdrasilErrorBody,
            crate::api::dto::yggdrasil::YggdrasilHasJoinedQuery,
            crate::api::dto::yggdrasil::YggdrasilJoinReq,
            crate::api::dto::yggdrasil::YggdrasilMeta,
            crate::api::dto::yggdrasil::YggdrasilMetaResp,
            crate::api::dto::yggdrasil::YggdrasilProfile,
            crate::api::dto::yggdrasil::YggdrasilProfileProperty,
            crate::api::dto::yggdrasil::YggdrasilProfileQuery,
            crate::api::dto::yggdrasil::YggdrasilRefreshReq,
            crate::api::dto::yggdrasil::YggdrasilRefreshResp,
            crate::api::dto::yggdrasil::YggdrasilSignoutReq,
            crate::api::dto::yggdrasil::YggdrasilTokenReq,
            crate::api::dto::yggdrasil::YggdrasilUser,
            crate::api::dto::yggdrasil::MinecraftServicesBanStatus,
            crate::api::dto::yggdrasil::MinecraftServicesBannedScopes,
            crate::api::dto::yggdrasil::MinecraftServicesCertificateResp,
            crate::api::dto::yggdrasil::MinecraftServicesChatPreferences,
            crate::api::dto::yggdrasil::MinecraftServicesFriendsPreferences,
            crate::api::dto::yggdrasil::MinecraftServicesKeyPair,
            crate::api::dto::yggdrasil::MinecraftServicesPathError,
            crate::api::dto::yggdrasil::MinecraftServicesPlayerAttributesResp,
            crate::api::dto::yggdrasil::MinecraftServicesPreferenceState,
            crate::api::dto::yggdrasil::MinecraftServicesPrivacyBlocklistResp,
            crate::api::dto::yggdrasil::MinecraftServicesPrivilege,
            crate::api::dto::yggdrasil::MinecraftServicesPrivileges,
            crate::api::dto::yggdrasil::MinecraftServicesPrivilegesResp,
            crate::api::dto::yggdrasil::MinecraftServicesProfanityFilterPreferences,
            crate::services::texture_service::MinecraftTextureMetadata,
            crate::services::texture_service::MinecraftTextureMetadataSource,
            crate::services::texture_service::MinecraftWardrobeTextureMetadata,
            crate::services::texture_service::TextureReportInfo,
            crate::services::texture_service::TextureReportUserInfo,
            crate::services::yggdrasil_service::MinecraftProfileInfo,

            crate::services::auth_service::AuthUserInfo,
            crate::services::ban_service::UserBanInfo,
            crate::services::ban_service::UserBanEventInfo,
            crate::services::admin_user_service::AdminUserInfo,
            crate::services::admin_user_service::CreateAdminUserOutput,
            crate::services::admin_user_service::DeleteAdminUserOutput,
            crate::services::auth_service::AuthSessionInfo,
            crate::services::auth_service::AuthTokenResponse,
            crate::services::auth_service::RegisterResponse,
            crate::services::auth_service::AccessClaims,
            crate::services::captcha_service::CaptchaChallengeResponse,
            crate::services::user_invitation_service::AdminUserInvitationInfo,
            crate::services::user_invitation_service::PublicUserInvitationInfo,
            crate::services::profile_service::AvatarInfo,
            crate::services::profile_service::UserProfileInfo,
            crate::services::passkey_service::PasskeyInfo,
            crate::services::passkey_service::PasskeyRegisterStartResp,
            crate::services::passkey_service::PasskeyLoginStartResp,
            crate::services::external_auth_service::ExternalAuthPublicProvider,
            crate::services::external_auth_service::ExternalAuthProviderKindInfo,
            crate::services::external_auth_service::AdminExternalAuthProviderInfo,
            crate::services::external_auth_service::ExternalAuthProviderTestCheck,
            crate::services::external_auth_service::ExternalAuthProviderTestResult,
            crate::services::external_auth_service::ExternalAuthStartLoginResponse,
            crate::api::routes::auth_external_auth::ExternalAuthFinishLoginResponse,
            crate::services::config_service::ConfigSchemaItem,
            crate::services::config_service::ConfigSchemaOption,
            crate::services::config_service::ConfigActionType,
            crate::services::config_service::PublicBranding,
            crate::services::config_service::PublicCaptchaConfig,
            crate::services::config_service::PublicFrontendConfig,
            crate::services::config_service::PublicTextureLibraryConfig,
            crate::services::config_service::PublicYggdrasilConfig,
            crate::services::config_service::SystemConfig,
            crate::services::config_service::SystemConfigUpdateResult,
            aster_forge_config::ConfigValue,
            crate::services::config_service::SystemConfigWarning,
            aster_forge_mail::TemplateVariableGroup,
            aster_forge_mail::TemplateVariableItem,
            crate::services::audit_service::AuditLogEntry,
            crate::services::audit_service::AuditLogFilterQuery,
            crate::services::audit_service::AuditPresentation,
            crate::services::audit_service::AuditPresentationMessage,
            crate::services::audit_service::AuditUserSummary,
            crate::services::admin_overview_service::AdminOverviewResp,
            crate::services::admin_overview_service::AdminOverviewServiceStatus,
            crate::services::admin_overview_service::AdminOverviewServiceStatusKind,
            crate::services::admin_overview_service::AdminOverviewSummary,
            crate::services::admin_overview_service::AdminOverviewSystemHealthComponent,
            crate::services::admin_overview_service::AdminOverviewSystemHealthStatus,
            crate::services::admin_overview_service::AdminOverviewSystemHealthSummary,
            crate::services::admin_overview_service::AdminOverviewTrendPoint,
            aster_forge_api::LimitQuery,
            aster_forge_api::SortOrder,
            aster_forge_api::IdCursor,
            aster_forge_api::StringIdCursor,
            aster_forge_api::SortOrderNameIdCursor,
            aster_forge_api::EnabledPriorityIdCursor,
            aster_forge_api::DateTimeIdCursor,
            aster_forge_api::DateTimeStringCursor,
            aster_forge_api::CreatedAtCursorQuery,
            aster_forge_api::UpdatedAtCursorQuery,
            crate::api::routes::auth::AuthSessionCursorQuery,
            crate::api::routes::auth::AuthCreatedAtCursorQuery,
            aster_forge_api::CursorPage<crate::services::config_service::SystemConfig, aster_forge_api::IdCursor>,
            aster_forge_api::CursorPage<crate::services::external_auth_service::ExternalAuthPublicProvider, aster_forge_api::StringIdCursor>,
            aster_forge_api::CursorPage<crate::services::external_auth_service::AdminExternalAuthProviderInfo, aster_forge_api::StringIdCursor>,
            aster_forge_api::CursorPage<crate::services::texture_service::MinecraftTextureTagInfo, aster_forge_api::SortOrderNameIdCursor>,
            aster_forge_api::CursorPage<crate::services::yggdrasil_session_forward_service::AdminYggdrasilSessionForwardServerInfo, crate::services::yggdrasil_session_forward_service::SessionForwardServerCursor>,
            aster_forge_api::CursorPage<crate::api::dto::yggdrasil::YggdrasilProfile, aster_forge_api::IdCursor>,
            aster_forge_api::CursorPage<crate::services::yggdrasil_service::MinecraftProfileInfo, aster_forge_api::IdCursor>,
            aster_forge_api::CursorPage<crate::services::texture_service::MinecraftWardrobeTextureMetadata, aster_forge_api::DateTimeIdCursor>,
            aster_forge_api::CursorPage<crate::services::texture_service::PublicTextureLibraryTextureMetadata, aster_forge_api::DateTimeIdCursor>,
            aster_forge_api::CursorPage<crate::services::texture_service::TextureReportInfo, aster_forge_api::DateTimeIdCursor>,
            aster_forge_api::CursorPage<crate::services::admin_user_service::AdminUserInfo, aster_forge_api::DateTimeIdCursor>,
            aster_forge_api::CursorPage<crate::api::dto::AccountUserBanInfo, aster_forge_api::DateTimeIdCursor>,
            aster_forge_api::CursorPage<crate::services::ban_service::UserBanInfo, aster_forge_api::DateTimeIdCursor>,
            aster_forge_api::CursorPage<crate::services::user_invitation_service::AdminUserInvitationInfo, aster_forge_api::DateTimeIdCursor>,
            aster_forge_api::CursorPage<crate::services::auth_service::AuthSessionInfo, aster_forge_api::DateTimeStringCursor>,
            aster_forge_api::CursorPage<crate::services::passkey_service::PasskeyInfo, aster_forge_api::DateTimeIdCursor>,
            aster_forge_api::CursorPage<crate::services::external_auth_service::ExternalAuthLinkInfo, aster_forge_api::DateTimeIdCursor>,
            aster_forge_api::CursorPage<crate::services::task_service::types::TaskInfo, aster_forge_api::DateTimeIdCursor>,
            crate::services::task_service::types::RuntimeSystemHealthComponent,
            crate::services::task_service::types::RuntimeSystemHealthResult,
            crate::services::task_service::types::RuntimeSystemHealthStatus,
            crate::services::task_service::types::RuntimeTaskPayload,
            crate::services::task_service::types::RuntimeTaskResult,
            crate::services::task_service::types::TaskCreatorSummary,
            crate::services::task_service::types::TaskInfo,
            crate::services::task_service::types::TaskPayload,
            crate::services::task_service::types::TaskPresentation,
            crate::services::task_service::types::TaskPresentationCode,
            crate::services::task_service::types::TaskPresentationMessage,
            crate::services::task_service::types::TaskResult,
            aster_forge_tasks::TaskStepInfo,
            aster_forge_tasks::TaskStepStatus,

            crate::entities::audit_log::Model,
            crate::entities::auth_session::Model,
            crate::entities::background_task::Model,
            crate::entities::external_auth_provider::Model,
            crate::entities::mail_outbox::Model,
            crate::entities::minecraft_profile::Model,
            crate::entities::minecraft_profile_texture::Model,
            crate::entities::minecraft_texture::Model,
            crate::entities::minecraft_texture_tag::Model,
            crate::entities::minecraft_texture_tag_binding::Model,
            crate::entities::user::Model,

            crate::types::user::UserRole,
            crate::types::user::OperatorScope,
            crate::types::user::UserBanScope,
            crate::types::user::UserBanStatus,
            crate::types::user::UserBanEventType,
            crate::types::user::UserStatus,
            crate::types::user::AvatarSource,
            crate::types::external_auth::ExternalAuthProviderKind,
            aster_forge_config::ConfigSource,
            aster_forge_config::ConfigValueType,
            aster_forge_config::ConfigVisibility,
            crate::types::task::BackgroundTaskKind,
            crate::types::task::BackgroundTaskStatus,
            aster_forge_mail::MailOutboxStatus,
            aster_forge_mail::MailTemplateCode,
            crate::types::audit::AuditAction,
            crate::types::audit::AuditEntityType,
            crate::types::yggdrasil::MinecraftTextureModel,
            crate::types::yggdrasil::MinecraftTextureType,
            crate::types::yggdrasil::MinecraftTextureVisibility,
            crate::types::yggdrasil::YggdrasilSessionForwardEndpointKind,
            crate::types::yggdrasil::YggdrasilSessionForwardProviderKind,
            crate::types::yggdrasil::YggdrasilSessionForwardServerSortBy,
            crate::services::yggdrasil_session_forward_service::AdminYggdrasilSessionForwardServerInfo,
            crate::api::dto::CreateYggdrasilSessionForwardServerReq,
            crate::api::dto::UpdateYggdrasilSessionForwardServerReq,
            crate::types::yggdrasil::MinecraftTextureLibraryStatus,
            crate::services::texture_service::MinecraftTextureTagInfo,
        ),
    ),
    tags(
        (name = "auth", description = "Authentication"),
        (name = "account", description = "Current-user account overview and activity"),
        (name = "external-auth", description = "External authentication"),
        (name = "profiles", description = "Current-user Minecraft profiles"),
        (name = "public", description = "Public frontend bootstrap config"),
        (name = "yggdrasil", description = "Yggdrasil and authlib-injector compatible endpoints"),
        (name = "admin", description = "Administrator operations"),
        (name = "health", description = "Health checks"),
    ),
)]
pub struct ApiDoc;

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "bearer",
            SecurityScheme::Http(Http::new(HttpAuthScheme::Bearer)),
        );
    }
}
